---
title: "PCA (timeOmics)"
format: docx
editor: visual
format: 
  docx:
    reference-doc:  F:/Aktenschrank/Kontakte/CQ_Bildung/Projekte/ABI/RClass2023/RScripts/quarto_template.docx
editor: visual
execute: 
  echo: false
  warning: false
  output: asis
fig-dpi: 300
fig-width: 6
fig-height: 8
tbl-cap-location: top
---

## **PCA timeOmics Package with timeOmics data**

```{r loading timeomics package}
###Lastest Bioconductor Release
## install BiocManager if not installed
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
## install timeOmics
BiocManager::install('timeOmics')

##Lastest Github version
install.packages("devtools")
# then load
library(devtools)
install_github("abodein/timeOmics")

#Load the package
library(timeOmics)
##Useful package to run this vignette
library(tidyverse)
library(conflicted)
library(writexl)
library(readxl)
library(wrappedtools)
conflicts_prefer(dplyr::select)
```

```{r loading simulated data}

timeOmics.simdata <- read_excel("F:/bioinformatic_weiterbildung_final/longitudinalOmics/Data/pivoted_metabolites.xlsx")
rawdata <- timeOmics.simdata

predvars <- FindVars(c('metabolite'))

sim.data <- rawdata |> select(predvars$names)

dim(sim.data) 
head(sim.data[,1:6])


```

# **Data preprocessing**

```{r Time-specific}

remove.low.cv <- function(X, cutoff = 0.5){
  # var.coef
  cv <- unlist(lapply(as.data.frame(X), 
                      function(x) abs(sd(x)/mean(x))))
  return(X[,cv > cutoff])
}

data.filtered <- remove.low.cv(sim.data, 0.5)
##nothing filtered

```

# **Time Modelling**

```{r lmms}
devtools::install_github("cran/lmms", force = TRUE)
library(lmms)

# numeric vector containing the sample time point information
time <- timeOmics.simdata$time
head(time)

# example of lmms
lmms.output <- lmms::lmmSpline(data = data.filtered, time = time,
                         sampleID = rownames(data.filtered), deri = FALSE,
                         basis = "p-spline", numCores = 4, timePredict = 1:9,
                         keepModels = TRUE)
modelled.data <- t(slot(lmms.output, 'predSpline'))

```

## Let's plot the modeled profiles.

average of each feature in all time points is zero

```{r vizualization}
# gather data
data.gathered <- modelled.data %>% as.data.frame() %>% 
  rownames_to_column("time") %>%
  mutate(time = as.numeric(time)) %>%
  pivot_longer(names_to="feature", values_to = 'value', -time)

# plot profiles
ggplot(data.gathered, aes(x = time, y = value, color = feature)) + geom_line() +
  theme_bw() + ggtitle("`lmms` profiles") + ylab("Feature expression") +
  xlab("Time")
```

## **Profile filtering**

#### for removing noisy profile

in this case if we run this part we will filter all the data

```{r noise filtering}
filter.res <- lmms.filter.lines(data = data.filtered, 
                                lmms.obj = lmms.output, time = time)
profile.filtered <- filter.res$filtered

```

## **Single-Omic longitudinal clustering**

```{r PCA}
# run pca
#we use data being filtered by lmms filter ( not profile.filtered )
profile.filtered<- data.filtered
pca.res <- pca(X = profile.filtered, ncomp = 5, scale=FALSE, center=FALSE)

# tuning ncomp
pca.ncomp <- getNcomp(pca.res, max.ncomp = 5, X = profile.filtered, 
                      scale = FALSE, center=FALSE)

pca.ncomp$choice.ncomp

#plot
plot(pca.ncomp)


```

```{r pca according silhouette coefficient}
# final model
pca.res <- pca(X = profile.filtered, ncomp = 3, scale = FALSE, center=FALSE)

# extract cluster
pca.cluster <- getCluster(pca.res)
head(pca.cluster)

```
