---
title: "PCA (timeOmics)"
format: 
  docx:
    reference-doc:  F:/bioinformatic_weiterbildung_final/longitudinalOmics/project/word_template.docx
editor: visual
execute: 
  echo: false
  warning: false
  output: asis
fig-dpi: 300
fig-width: 6
fig-height: 8
tbl-cap-location: top
---

## **PCA analysis for timeOmics Data**

```{r loading timeomics package}
###Lastest Bioconductor Release
## install BiocManager if not installed
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
## install timeOmics
BiocManager::install('timeOmics')

##Lastest Github version
install.packages("devtools")
# then load
library(devtools)
install_github("abodein/timeOmics")

#Load the package
library(timeOmics)
##Useful package to run this vignette
library(tidyverse)
library(conflicted)
library(writexl)
library(readxl)
library(wrappedtools)

```

```{r loading timeomics data}
data("timeOmics.simdata")
sim.data <- timeOmics.simdata$sim

dim(sim.data) 
head(sim.data[,1:6])
original_simdata <- sim.data 

###saving data for showing
rawdata <- sim.data 

modified_data <- rawdata %>% as.data.frame() |> 
  rownames_to_column(var = "ID") |> 
  separate(col = ID,
           into = c('PatID','time'),
           sep = 1,
           remove = TRUE)


write_xlsx(modified_data, "F:/bioinformatic_weiterbildung_final/longitudinalOmics/Data/timeOmics_data.xlsx")

#slice the first column
sim.data <- read_excel(path = "F:/bioinformatic_weiterbildung_final/longitudinalOmics/Data/timeOmics_data.xlsx",
                 range = 'A1:C46')
sliced_c0 <- sim.data

#slicepivot
sliced_pivot <- sliced_c0 |>
  pivot_wider(names_from = time,
              values_from = c0)

c0<-sliced_pivot
write_xlsx(c0, "F:/bioinformatic_weiterbildung_final/longitudinalOmics/Data/c0.xlsx")


sim.data <- original_simdata
predvars <- FindVars(c('c'))

```
